apiVersion: v2
name: soperator-checks
description: Soperator checks controller for ActiveCheck resources.
type: application
version: 3.0.5-ps.1
appVersion: "3.0.5"
annotations:
  soperator.nebius.com/upstream-release: "3.0.5"
