from __future__ import annotations

import os
import socket
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any

from ..tunnel_state import collect_tunnel_state
from .local_commands import CURRENT, run

IPSEC_CONF = Path("/etc/ipsec.conf")
STRONGSWAN_CONF_DIR = Path("/etc/strongswan.d/charon")
SWANCTL_CONF = Path("/etc/swanctl/swanctl.conf")
VICI_SOCKET = Path("/var/run/charon.vici")

_LEGACY_MANAGED_XFRM_IF_CONF = """# generated by nebius-vpngw-agent
xfrm_if {
  load = yes
}
"""


def _write_secret_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=str(path.parent),
            prefix=f"{path.name}.",
            delete=False,
        ) as tmp:
            tmp_path = Path(tmp.name)
            # codeql[py/clear-text-storage-sensitive-data] - strongSwan requires on-disk PSKs; file perms are locked to 0600.
            tmp.write(content)
        os.chmod(tmp_path, 0o600)
        os.replace(tmp_path, path)
        os.chmod(path, 0o600)
    finally:
        if tmp_path is not None and tmp_path.exists():
            tmp_path.unlink()


def _wait_for_vici_socket(timeout_seconds: float = 15.0, interval_seconds: float = 0.5) -> bool:
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        try:
            with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as probe:
                probe.settimeout(min(interval_seconds or 0.1, 0.5))
                probe.connect(str(VICI_SOCKET))
            return True
        except OSError:
            pass
        time.sleep(interval_seconds)
    return False


class StrongSwanRenderer:
    def _collect_tunnel_state(
        self, cfg: dict[str, Any]
    ) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
        return collect_tunnel_state(cfg)

    def build_interface_endpoints(self, cfg: dict[str, Any]) -> list[dict]:
        _, _, interface_endpoints = self._collect_tunnel_state(cfg)
        return interface_endpoints

    def render_and_apply(
        self,
        cfg: dict[str, Any],
        *,
        activate: bool = True,
        rendered_files: dict[Path, str | None] | None = None,
    ) -> list[dict[str, Any]]:
        """Render strongSwan config based on resolved per-VM YAML.

        Uses swanctl (VICI) to load per-tunnel connections with if_id_in/out for deterministic
        XFRM binding. Writes a minimal ipsec.conf to start charon via strongswan-starter.
        Supports IKEv1/IKEv2, configurable crypto proposals, DPD, and both BGP and static routing
        using XFRM interfaces.
        """
        preview = rendered_files is not None

        def write(path: Path, content: str) -> None:
            if rendered_files is not None:
                rendered_files[path] = content
            else:
                path.write_text(content, encoding="utf-8")

        tunnels, secrets, interface_endpoints = self._collect_tunnel_state(cfg)

        # Write strongSwan plugin configuration based on mode
        if not preview:
            STRONGSWAN_CONF_DIR.mkdir(parents=True, exist_ok=True)

        # Always disable automatic route installation (we manage routes via agent)
        install_routes_conf = """# generated by nebius-vpngw-agent
# Disable automatic route installation - agent manages routes
charon {
  install_routes = no
}
"""
        install_routes_path = STRONGSWAN_CONF_DIR / "install-routes.conf"
        write(install_routes_path, install_routes_conf)
        print(f"[StrongSwan] Wrote {install_routes_path}")

        # XFRM interfaces are kernel/iproute2 objects linked to CHILD_SAs by
        # if_id_in/out.  There is no charon xfrm_if plugin.  Remove only the
        # exact legacy file written by older nebius-vpngw releases so upgraded
        # gateways stop requesting a nonexistent plugin without touching a
        # caller-owned file at the same path.
        xfrm_conf_path = STRONGSWAN_CONF_DIR / "xfrm_if.conf"
        if (
            xfrm_conf_path.exists()
            and xfrm_conf_path.read_text(encoding="utf-8") == _LEGACY_MANAGED_XFRM_IF_CONF
        ):
            if rendered_files is not None:
                rendered_files[xfrm_conf_path] = None
            else:
                xfrm_conf_path.unlink()
            print(f"[StrongSwan] Removed obsolete managed {xfrm_conf_path}")

        # This product implements VM-level HA itself and must not activate
        # strongSwan's unrelated ClusterIP/state-synchronization HA plugin.
        # Ubuntu enables that plugin by default even without local/remote sync
        # addresses, which produces a warning on every daemon start.
        ha_conf = """# generated by nebius-vpngw-agent
ha {
  load = no
}
"""
        ha_conf_path = STRONGSWAN_CONF_DIR / "zz-nebius-vpngw-ha.conf"
        write(ha_conf_path, ha_conf)
        print(f"[StrongSwan] Wrote {ha_conf_path} (disabled unused HA plugin)")

        # Enable NAT keepalives to prevent NAT mapping timeout
        # Critical for UDP-encapsulated ESP (NAT-T) - prevents tunnel state desync
        keepalive_conf = """# generated by nebius-vpngw-agent
# Enable NAT keepalives to maintain NAT bindings for UDP-encap ESP
# Prevents tunnel state desync where tunnel shows ESTABLISHED but stops forwarding
charon {
  keep_alive = 20s
}
"""
        keepalive_conf_path = STRONGSWAN_CONF_DIR / "keepalive.conf"
        write(keepalive_conf_path, keepalive_conf)
        print(f"[StrongSwan] Wrote {keepalive_conf_path} (enabled NAT keepalives: 20s)")

        # Disable VTI plugin if present
        vti_conf_path = STRONGSWAN_CONF_DIR / "vti.conf"
        if vti_conf_path.exists():
            vti_conf = """# generated by nebius-vpngw-agent
vti {
  load = no
}
"""
            write(vti_conf_path, vti_conf)
            print(f"[StrongSwan] Wrote {vti_conf_path} (disabled vti plugin)")

        # Write netplan override to disable IPv4 link-local addressing on eth0
        # This prevents DHCP from injecting the broad 169.254.0.0/16 route
        # SAFE: Uses link-local: [ipv6] instead of use-routes: false
        netplan_override_text = """# generated by nebius-vpngw-agent
# Disable IPv4 link-local (APIPA 169.254/16) to prevent conflicts with VPN inner IPs
# This is SAFE - it does NOT block DHCP routes (default gateway, DNS, etc.)
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        use-dns: true
        use-routes: true
      link-local: [ ipv6 ]
"""
        netplan_dir = NETPLAN_DIR
        if not preview:
            netplan_dir.mkdir(parents=True, exist_ok=True)
        netplan_override = netplan_dir / "99-nebius-vpngw.yaml"
        write(netplan_override, netplan_override_text)
        print(f"[StrongSwan] Wrote {netplan_override} (disabled IPv4 link-local)")

        # Apply netplan configuration
        if activate and not preview:
            result = run(["netplan", "apply"], capture_output=True, text=True)
            if result.returncode == 0:
                print("[StrongSwan] ✓ Applied netplan configuration")
            else:
                print(f"[StrongSwan] ⚠ netplan apply failed: {result.stderr}")

        # Write minimal ipsec.conf so strongswan-starter can launch charon without parsing tunnels.
        ipsec_text = [
            "# generated by nebius-vpngw-agent",
            "config setup",
            '    charondebug="ike 1, knl 1, net 1, cfg 1"',
            "    uniqueids=no",
            "",
        ]
        write(IPSEC_CONF, "\n".join(ipsec_text) + "\n")
        print(f"[StrongSwan] Wrote {IPSEC_CONF} (starter-only config)")

        # Write swanctl.conf (includes secrets)
        if not preview:
            SWANCTL_CONF.parent.mkdir(parents=True, exist_ok=True)
        swanctl_lines = ["# generated by nebius-vpngw-agent", "connections {"]
        for tun in tunnels:
            name = tun["name"]
            swanctl_lines.append(f"  {name} {{")
            swanctl_lines.append(f"    version = {tun['ike_version']}")
            swanctl_lines.append("    local_addrs = %any")
            swanctl_lines.append(f"    remote_addrs = {tun['remote_public_ip']}")
            if tun["ike_props"]:
                swanctl_lines.append(f"    proposals = {','.join(tun['ike_props'])}")
            swanctl_lines.append(f"    rekey_time = {int(tun['ike_life'])}s")
            # Loading a start_action connection and receiving a simultaneous peer
            # initiation must converge to one IKE SA for the peer identity.
            swanctl_lines.append("    unique = replace")
            swanctl_lines.append("    local {")
            swanctl_lines.append("      auth = psk")
            if tun["local_public_ip"]:
                swanctl_lines.append(f"      id = {tun['local_public_ip']}")
            swanctl_lines.append("    }")
            swanctl_lines.append("    remote {")
            swanctl_lines.append("      auth = psk")
            swanctl_lines.append(f"      id = {tun['remote_public_ip']}")
            swanctl_lines.append("    }")
            dpd = tun.get("dpd") or {}
            if dpd:
                swanctl_lines.append(f"    dpd_delay = {int(dpd.get('interval_seconds', 30))}s")
                swanctl_lines.append(f"    dpd_timeout = {int(dpd.get('timeout_seconds', 120))}s")
            swanctl_lines.append("    children {")
            swanctl_lines.append(f"      {name} {{")
            swanctl_lines.append(f"        local_ts = {','.join(tun['local_ts'])}")
            swanctl_lines.append(f"        remote_ts = {tun['remote_ts']}")
            if tun["esp_props"]:
                swanctl_lines.append(f"        esp_proposals = {','.join(tun['esp_props'])}")
            swanctl_lines.append(f"        rekey_time = {int(tun['esp_life'])}s")
            swanctl_lines.append("        mode = tunnel")
            swanctl_lines.append(f"        start_action = {'start' if activate else 'none'}")
            swanctl_lines.append(f"        close_action = {'restart' if activate else 'none'}")
            swanctl_lines.append(f"        if_id_in = {tun['if_id']}")
            swanctl_lines.append(f"        if_id_out = {tun['if_id']}")
            swanctl_lines.append("      }")
            swanctl_lines.append("    }")
            swanctl_lines.append("  }")
        swanctl_lines.append("}")

        if secrets:
            swanctl_lines.append("secrets {")
            for idx, secret in enumerate(secrets, start=1):
                swanctl_lines.append(f"  ike-psk-{idx} {{")
                swanctl_lines.append(f"    id-1 = {secret['local_id']}")
                swanctl_lines.append(f"    id-2 = {secret['remote_id']}")
                swanctl_lines.append(f'    secret = "{secret["secret"]}"')
                swanctl_lines.append("  }")
            swanctl_lines.append("}")

        swanctl_content = "\n".join(swanctl_lines) + "\n"
        if rendered_files is not None:
            rendered_files[SWANCTL_CONF] = swanctl_content
        else:
            _write_secret_file(SWANCTL_CONF, swanctl_content)
        print(f"[StrongSwan] Wrote {SWANCTL_CONF} (permissions: 0600)")

        # Enable VICI plugin so swanctl can talk to charon
        vici_conf = """# generated by nebius-vpngw-agent
vici {
  load = yes
}
"""
        vici_conf_path = STRONGSWAN_CONF_DIR / "vici.conf"
        write(vici_conf_path, vici_conf)
        print(f"[StrongSwan] Wrote {vici_conf_path} (enabled vici plugin)")

        # Reload strongSwan to pick up new configs
        if not activate or preview:
            return interface_endpoints

        try:
            run(
                ["systemctl", "restart", "strongswan-starter"],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=20,
            )
        except Exception as e:
            print(f"[StrongSwan] WARNING: failed to restart strongswan-starter: {e}")

        # Load swanctl connections and secrets via VICI
        try:
            load_result = None
            for attempt in range(1, 4):
                if not _wait_for_vici_socket():
                    print("[StrongSwan] WARNING: VICI socket not ready; retrying swanctl load")
                    time.sleep(1)
                    continue
                load_result = run(
                    ["swanctl", "--load-all"],
                    check=False,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    timeout=20,
                )
                if load_result.returncode == 0:
                    break
                print(
                    f"[StrongSwan] WARNING: swanctl load failed (attempt {attempt}): "
                    f"{(load_result.stderr or '').strip()}"
                )
                time.sleep(1)

            if not load_result or load_result.returncode != 0:
                budget = CURRENT.get()
                if budget is not None:
                    budget.failures.append("swanctl_load")
                print("[StrongSwan] WARNING: swanctl load did not succeed")
        except Exception as e:
            print(f"[StrongSwan] WARNING: failed to load swanctl config: {e}")

        # Return interface configuration for external management (XFRM device creation, routing)
        # XFRM interfaces must be created externally before/after strongSwan starts
        return interface_endpoints


NETPLAN_DIR = Path("/etc/netplan")
