from __future__ import annotations

import os
import socket
import tempfile
from pathlib import Path
from types import SimpleNamespace

from nebius_vpngw.agent import strongswan_renderer
from nebius_vpngw.agent.strongswan_renderer import (
    StrongSwanRenderer,
    _wait_for_vici_socket,
    _write_secret_file,
)


def test_vici_readiness_rejects_a_stale_unix_socket(tmp_path, monkeypatch) -> None:
    del tmp_path
    with tempfile.TemporaryDirectory(prefix="vici-", dir="/tmp") as directory:
        socket_path = Path(directory) / "v"
        listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        listener.bind(str(socket_path))
        listener.listen(1)
        monkeypatch.setattr(strongswan_renderer, "VICI_SOCKET", socket_path)

        assert _wait_for_vici_socket(timeout_seconds=0.1, interval_seconds=0.01)

        listener.close()

        assert not _wait_for_vici_socket(timeout_seconds=0.02, interval_seconds=0.01)
        socket_path.unlink()


def test_collect_tunnel_state_uses_defaults_and_local_prefixes(sample_config: dict) -> None:
    sample_config["connections"][0]["tunnels"].append(
        {
            "name": "tunnel-no-remote-ip",
            "remote_public_ip": None,
            "inner_cidr": "169.254.19.0/30",
            "inner_local_ip": "169.254.19.1",
            "inner_remote_ip": "169.254.19.2",
        }
    )
    sample_config["connections"][0]["tunnels"].append(
        {
            "name": "tunnel-ikev1-disabled",
            "ike_version": 1,
            "remote_public_ip": "198.51.100.11",
            "inner_cidr": "169.254.20.0/30",
            "inner_local_ip": "169.254.20.1",
            "inner_remote_ip": "169.254.20.2",
            "psk": "psk-2",
        }
    )

    tunnels, secrets, interfaces = StrongSwanRenderer()._collect_tunnel_state(sample_config)

    assert [tunnel["name"] for tunnel in tunnels] == ["tunnel-1"]
    assert tunnels[0]["if_id"] == 100
    assert tunnels[0]["local_ts"] == ["169.254.18.224/30", "10.0.0.0/16"]
    assert secrets == [
        {
            "local_id": "%any",
            "remote_id": "198.51.100.10",
            "secret": "test-only-static-routing-validation-psk",
        }
    ]
    assert interfaces == [
        {
            "name": "xfrm0",
            "mode": "static",
            "local_inner_ip": "169.254.18.225",
            "remote_inner_ip": "169.254.18.226",
            "cidr": "169.254.18.224/30",
            "local_public_ip": None,
            "remote_public_ip": "198.51.100.10",
            "remote_prefixes": ["203.0.113.0/24"],
            "if_id": 100,
        }
    ]


def test_write_secret_file_uses_secure_permissions(tmp_path) -> None:
    output_path = tmp_path / "nested" / "swanctl.conf"

    _write_secret_file(output_path, "secret = test\n")

    assert output_path.read_text(encoding="utf-8") == "secret = test\n"
    assert os.stat(output_path).st_mode & 0o777 == 0o600


def test_wait_for_vici_socket_uses_configured_path(tmp_path, monkeypatch) -> None:
    del tmp_path
    with tempfile.TemporaryDirectory(prefix="vici-", dir="/tmp") as directory:
        socket_path = Path(directory) / "v"
        monkeypatch.setattr(strongswan_renderer, "VICI_SOCKET", socket_path)

        assert not _wait_for_vici_socket(timeout_seconds=0.0, interval_seconds=0.0)

        listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        listener.bind(str(socket_path))
        listener.listen(1)
        try:
            assert _wait_for_vici_socket(timeout_seconds=0.1, interval_seconds=0.01)
        finally:
            listener.close()
            socket_path.unlink()



def test_active_render_uses_one_duplicate_safe_start_path(
    tmp_path,
    monkeypatch,
    sample_config: dict,
) -> None:
    calls: list[list[str]] = []

    def run(argv, **kwargs):
        calls.append(argv)
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    monkeypatch.setattr(strongswan_renderer, "STRONGSWAN_CONF_DIR", tmp_path / "strongswan.d")
    monkeypatch.setattr(strongswan_renderer, "IPSEC_CONF", tmp_path / "ipsec.conf")
    monkeypatch.setattr(strongswan_renderer, "SWANCTL_CONF", tmp_path / "swanctl.conf")
    monkeypatch.setattr(strongswan_renderer, "NETPLAN_DIR", tmp_path / "netplan")
    monkeypatch.setattr(strongswan_renderer, "_wait_for_vici_socket", lambda: True)
    monkeypatch.setattr(strongswan_renderer.subprocess, "run", run)
    strongswan_dir = tmp_path / "strongswan.d"
    strongswan_dir.mkdir()
    (strongswan_dir / "xfrm_if.conf").write_text(
        strongswan_renderer._LEGACY_MANAGED_XFRM_IF_CONF,
        encoding="utf-8",
    )

    StrongSwanRenderer().render_and_apply(sample_config)

    rendered = (tmp_path / "swanctl.conf").read_text(encoding="utf-8")
    assert not (strongswan_dir / "xfrm_if.conf").exists()
    assert (strongswan_dir / "zz-nebius-vpngw-ha.conf").read_text(encoding="utf-8") == (
        "# generated by nebius-vpngw-agent\nha {\n  load = no\n}\n"
    )
    assert "    unique = replace\n" in rendered
    assert "        start_action = start\n" in rendered
    assert ["swanctl", "--load-all"] in calls
    assert not any("--initiate" in argv for argv in calls)


def test_render_preserves_caller_owned_xfrm_if_plugin_file(
    tmp_path,
    monkeypatch,
    sample_config: dict,
) -> None:
    strongswan_dir = tmp_path / "strongswan.d"
    strongswan_dir.mkdir()
    custom = "# operator-owned\nxfrm_if { load = no }\n"
    (strongswan_dir / "xfrm_if.conf").write_text(custom, encoding="utf-8")

    monkeypatch.setattr(strongswan_renderer, "STRONGSWAN_CONF_DIR", strongswan_dir)
    monkeypatch.setattr(strongswan_renderer, "IPSEC_CONF", tmp_path / "ipsec.conf")
    monkeypatch.setattr(strongswan_renderer, "SWANCTL_CONF", tmp_path / "swanctl.conf")
    monkeypatch.setattr(strongswan_renderer, "NETPLAN_DIR", tmp_path / "netplan")
    monkeypatch.setattr(strongswan_renderer, "_wait_for_vici_socket", lambda: True)
    monkeypatch.setattr(
        strongswan_renderer.subprocess,
        "run",
        lambda *args, **kwargs: SimpleNamespace(returncode=0, stdout="", stderr=""),
    )

    StrongSwanRenderer().render_and_apply(sample_config, activate=False)

    assert (strongswan_dir / "xfrm_if.conf").read_text(encoding="utf-8") == custom
