{{- if .Values.monitoring.serviceMonitor.enabled }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
{{- fail "monitoring.serviceMonitor.enabled=true requires ServiceMonitor CRD (monitoring.coreos.com/v1)" }}
{{- end }}
{{- $scheme := .Values.monitoring.serviceMonitor.scheme -}}
{{- if not $scheme }}
{{- $scheme = ternary "https" "http" .Values.tls.enabled -}}
{{- end }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mysterybox-webhook.fullname" . }}
  labels:
    {{- include "mysterybox-webhook.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mysterybox-webhook.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      honorLabels: {{ .Values.monitoring.serviceMonitor.honorLabels }}
      scheme: {{ $scheme | quote }}
      {{- with .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
