version: v1

client_info:
  client_name: example-client
  nebius:
    tenant_id: tenant-REDACTED
    project_id: project-REDACTED
    region_id: us-central1
  notifications:
    inventory_markdown: true
    email: ops@example.com

infra:
  components:
    - id: mk8s
      enabled: true
      inputs:
        parent_id: project-REDACTED
        cluster_name: example-cluster
        subnet_id: vpcsubnet-REDACTED
        cpu_nodes_platform: cpu-d3
        cpu_nodes_preset: 4vcpu-16gb
        gpu_enabled: false

apps:
  charts:
    - id: gateway-helm
      group: platform
      enabled: true
      repo: oci://docker.io/envoyproxy/gateway-helm
      version: 1.7.0
      namespace: envoy-gateway-system
      release-name: envoy-gateway
      values: {}
