apiVersion: v2
name: nccl-test
description: Render an ephemeral Kubeflow MPIJob that runs NVIDIA NCCL all_reduce_perf
type: application
version: 0.2.6
appVersion: 0.2.0
kubeVersion: ">=1.28.0-0"
home: https://github.com/NVIDIA/nccl-tests
sources:
  - https://github.com/NVIDIA/nccl-tests
  - https://docs.nebius.com/kubernetes/gpu/nccl-test
maintainers:
  - name: Nebius PS Services
    url: https://github.com/nebius/nebius-ps-services
keywords:
  - nvidia
  - nccl
  - mpi
  - kubeflow
  - benchmark
