{{- $root := . -}}
{{- if hasKey .Values "hostUsers" -}}
{{- range $name, $check := .Values.checks }}
{{- if and $check.enabled (not (hasKey $check "podTemplateNameRef")) }}
{{- $hostUsers := $root.Values.hostUsers -}}
{{- if hasKey $check "hostUsers" -}}
{{- $hostUsers = $check.hostUsers -}}
{{- end }}
{{- $image := $root.Values.images.k8sJob -}}
{{- if eq $check.checkType "slurmJob" -}}
{{- $spec := default dict $check.slurmJobSpec -}}
{{- $jobContainer := default dict $spec.jobContainer -}}
{{- $image = default $root.Values.images.slurmJob $jobContainer.image -}}
{{- else if eq $check.checkType "k8sJob" -}}
{{- $spec := default dict $check.k8sJobSpec -}}
{{- $jobContainer := default dict $spec.jobContainer -}}
{{- $image = default $root.Values.images.k8sJob $jobContainer.image -}}
{{- end }}
---
apiVersion: v1
kind: PodTemplate
metadata:
  name: {{ $name | quote }}
  labels:
{{ include "soperator-activechecks.labels" $root | indent 4 }}
template:
  spec:
    hostUsers: {{ $hostUsers }}
    restartPolicy: Never
    containers:
      - name: {{ $name | quote }}
        image: {{ tpl $image $root | quote }}
{{- end }}
{{- end }}
{{- end }}
